# Exercise 1: NumPy Arrays

## 1. Introduction to NumPy arrays

### Aim: Introduce the basic NumPy array creation and indexing

Issues covered:

- Importing NumPy
- Creating an array from a list
- Creating arrays of zeroes or ones
- Understanding array type codes
- Array indexing and slicing

Import the `numpy` library as `np`

In [1]:
import numpy as np

### Let's create a numpy array from a list.

Create a with values 1 to 10 and assign it to the variable `x`

In [32]:
x = np.array(np.arange(0, 11))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


Create a numpy integer array using `x` and print its `dtype`

In [29]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.int32)
print(x.dtype)

int32


Create a numpy float array using `x` and print its `dtype`

In [6]:
x = np.array([[2, 3, -5], [21, -2, 1]], dtype =np.float64)
print(x.dtype)

float64


### Let's create arrays in different way.

- Create an array of shape (2, 3, 4) of zeros
- Create an array of shape (2, 3, 4) of ones.
- Create an array with values 0 to 999 using the `np.arange` function.

In [13]:
zeros = np.zeros((2, 3, 4))
ones = np.ones((2, 3, 4))
arr = np.arange(0, 999)

### Let's look at indexing and slicing arrays.

Create an array from the list `[2, 3.2, 5.5, -6.4, -2.2, 2.4]` and assign it to the variable `a`

- Do you know what `a[1]` will equal? Print to see.
- Try print `a[1:4]` to see what that equals.

In [16]:
a = np.array([2, 3.2, 5.5, -6.4, -2.2, 2.4])
a[1:4]

array([ 3.2,  5.5, -6.4])

Create a 2-D array from the following list and assign it to the variable `a`:
```python
[
    [2, 3.2, 5.5, -6.4, -2.2, 2.4],
    [1, 22, 4, 0.1, 5.3, -9],
    [3, 1, 2.1, 21, 1.1, -2]
]
```

Can you guess what the following slices are equal to? Print them to check your understanding.

- `a[:, 3]`
- `a[1:4, 0:4]`
- `a[1:, 2]`

In [18]:
a = np.array([
    [2, 3.2, 5.5, -6.4, -2.2, 2.4],
    [1, 22, 4, 0.1, 5.3, -9],
    [3, 1, 2.1, 21, 1.1, -2]
])

array([-6.4,  0.1, 21. ])

## 2. Interrogating and manipulating arrays

### Aim: Learn how to interrogate and manipulate NumPy Arrays

Issues covered:

- Interrogating the properties of an array
- Manipulating arrays to change their properties

### Let's interrogate an array to find out it's characteristics

Create a 2-D array of shape (2, 4) containing two lists `range(4)` and `range(10, 14)`, assign it to the vairable `arr`

- Print the shape of the array
- Print the size of the array
- Print and maximum and minimum of the array

In [37]:
range4 = np.arange(4)
range10_14 = np.arange(10, 14)

arr = np.array([range4, range10_14])
print("shape = {0}, size = {1}, max = {2}, min = {3}".format(arr.shape, arr.size, np.max(arr), np.min(arr)))

shape = (2, 4), size = 8, max = 13, min = 0


### Let's generate new arrays by modifying our array

Continue to use the array, `arr`, as defined above

- Print the array re-shaped to (2, 2, 2)
- Print the array transposed
- Print the array flattened to a single dimension
- Print the array converted to floats

In [44]:
print("reshaped = \n {0},\n transposed = \n {1}, \n flattened = \n {2}, \n floats = \n{3}".format(np.reshape(arr, (2, 2, 2)), np.transpose(arr), np.ravel(arr), np.array(arr, dtype=np.float64)))

reshaped = 
 [[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]],
 transposed = 
 [[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]], 
 flattened = 
 [ 0  1  2  3 10 11 12 13], 
 floats = 
[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]]


## 3. Array calculation and operations

### Aim: Use NumPy arrays in mathematical calculations

Issues covered:

- Mathematical operations with arrays
- Mathematical operations mixing scalars and arrays
- Comparison operators and Boolean operations on arrays
- Using the `where` method
- Writing a function to work on arrays

### Let's perform some array calculations

Create a 2-D array of shape (2, 4) containing two lists `range(4)` and `range(10, 14)`, assign it to the vairable `a`

Create an array from a list `[2, -1, 1, 0]` and assign it to the variable `b`

- Multiply array `a` by `b` and print the result. Do you understand how numpy has used its *broadcasting* feature to do the calculation even though the arrays are different shapes?
- Multiply array `b` by 100 and assign the result to variable `b1` with `np.multiply`
- Multiply array `b` by 100.0 and assign the result to the variable `b2` with `np.multiply`
- Print the arrays `b1` and `b2`
- Print `b1 == b2`, are they the same?
- Why do they display differently? Interrogate the `dtype` of each array to find out why

In [53]:
a = arr
b = np.array([2, -1, 1, 0])
print("a x b")
print(a*b)

b1 = np.multiply(b, 100)
print("b1")
print(b1)

b2 = np.multiply(b, 100.0)

print("b2")
print(b2)
print(b1 == b2)

print(b1.dtype)
print(b2.dtype)

a x b
[[  0  -1   2   0]
 [ 20 -11  12   0]]
b1
[ 200 -100  100    0]
b2
[ 200. -100.  100.    0.]
[ True  True  True  True]
int64
float64


### Let's look at array comparisons

Create an array of values 0 to 9 and assign it to the variable `arr`

- Print two different way of expressing the condition where the array is less than 3.
- Create a numpy condition where `arr` is less than 3 OR greater than 8.
- Use the `where` function to create a new array where the value is `arr*5` if the above condition is `True` and `arr-5` where the condition is `False`

In [60]:
arr = np.array(np.arange(0, 10))

condition1 = arr < 3
condition2 = np.less(arr, 3)

print(condition1, condition2)

condition3 = np.logical_and(arr < 3, arr > 8)

print(condition3)

answer = np.where(condition3, arr*5, arr-5)

print(answer)

[ True  True  True False False False False False False False] [ True  True  True False False False False False False False]
[False False False False False False False False False False]
[-5 -4 -3 -2 -1  0  1  2  3  4]


### Let's implement a mathematical function that works on arrays.

Write a function that takes a 2-D array of horizontal zonal (east-west) wind components (`u`, in m/s) and a 2-D array of horizontal meridional (north-south) wind componenets (`v`, in m/s)
and returns an array of the magnitudes of the total wind.
Include a test for the overall magnitude: if it is less than 0.1 then set it equal to 0.1 (We might presume this particular domain has no non-zero winds and that only winds above 0.1 m/s constitute "good" data while those below are indistinguishable from the minimum due to noise)

The return value should be an array of the same shape and type as the input arrays. The magnitude of the wind can be calculated as the square root of the sum of the squares of the `u` and `v` winds.

- Test your function on `u = [[4, 5, 6], [2, 3, 4]]` and `v = [[2, 2, 2], [1, 1, 1]]` values.
- Test your function on `u = [[4, 5, 0.01], [2, 3, 4]]` and `v = [[2, 2, 0.03], [1, 1, 1]]` values. Does your default minimum magnitude get used?

In [77]:
def calc_magnitude(u, v):
    total_wind = np.sqrt(np.multiply(u, u) + np.multiply(v, v))

    condition = np.less(total_wind, 0.1)
    corrected_wind = np.where(condition, 0.1, total_wind)

    return corrected_wind

In [78]:
u = [[4, 5, 6], [2, 3, 4]]
v = [[2, 2, 2], [1, 1, 1]]

In [79]:
calc_magnitude(u, v)

array([[4.47213595, 5.38516481, 6.32455532],
       [2.23606798, 3.16227766, 4.12310563]])

In [80]:
u2 = [[4, 5, 0.01], [2, 3, 4]] 
v2 = [[2, 2, 0.03], [1, 1, 1]]

calc_magnitude(u2, v2)

array([[4.47213595, 5.38516481, 0.1       ],
       [2.23606798, 3.16227766, 4.12310563]])

## 4. Working with missing values

### Aim: An introduction to masked arrays to represent missing values

Issues covered:

- Creating a masked array
- Masking certain values in an array
- Using the `masked_where` function to create a masked array
- Applying a mask to an existing array
- Performing calculation with masked arrays

### Let's create a masked array and play with it

Import the `numpy.ma` module as `MA`

In [63]:
import numpy.ma as MA

Create a masked array from a list of values (0 to 9) with a `fill_value` of -999 and assign it to the variable `marr`

- Print the array to view its values. Print the `fill_value` attribute.
- Mask the third value in the array using `MA.masked`, print the array to view how it has changed.
- Print the mask associated with the array (i.e. `marr.mask`)

In [86]:
data = np.array(np.arange(0, 10))
marr = MA.masked_array(data, fill_value =-999)
print(marr, marr.fill_value)

marr[2] = MA.masked

print(marr)
print(marr.mask)

[0 1 2 3 4 5 6 7 8 9] -999
[0 1 -- 3 4 5 6 7 8 9]
[False False  True False False False False False False False]


Create a new masked array called `narr` that is equal to `marr` where `marr` is less than 7 and masked otherwise.

- Print the array to view its values.
- Print its missing value (i.e. `narr.fill_value`)
- Print an array that converts `narr` so that the missing values are represented by the missing value (i.e. `MA.filled`). Assign it to `farr`
- What is the type of the `farr`

In [97]:
narr = MA.masked_greater(marr, 7)

farr = MA.filled(narr, fill_value = narr.fill_value)
print(farr)

[   0    1 -999    3    4    5    6    7 -999 -999]


### Let's create a masked array based on a condition.

- Create a masked array of values 1 to 8 and assign it to the variable `m1`, print `m1`
- Re-shape the array to the shape `(2, 4)` and assign it to the variable `m2`, print `m2`
- Mask values of `m2` greater than 6 and assign the result to the variable `m3`, print `m3`
- Print `m3` multiplied by 100
- Subtract `m3` by a normal numpy array of `ones` that is the same shape as `m3` and assign it to the variable `m4`, print `m4`
- Is `m4` a normal array or masked array?

In [108]:
m1 = MA.masked_array(data = np.array(np.arange(1, 9)))
print(m1)

m2 = np.reshape(m1, (2, 4))
print(m2)

m3 = MA.masked_greater(m2, 6)
print(m3)
print(np.multiply(m3, 100))

m4 = m3 - (np.ones((2, 4)))
print(m4)


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 -- --]]
[[100 200 300 400]
 [500 600 -- --]]
[[0.0 1.0 2.0 3.0]
 [4.0 5.0 -- --]]
